---
- name: copy repo
  become: true
  become_user: root
  copy:
    src: /home/ubuntu/ansible-in-ci-cd-project/
    dest: "{{ path_to_project }}"
    remote_src: true
    directory_mode:
- name: Build an image
  docker_image:
    build:
      path: "{{ path_to_project }}"
    name: "{{ full_image_name }}"
    tag: "{{ tag }}"
    source: build
    force_source: yes
