---
- name: clone repo
  git:
    repo: "{{ repo_to_build }}"
    dest: "{{ where_repo_should_be }}"
- name: Build an image
  docker_image:
    build:
      path: "{{ path_to_dockerfile }}"
    name: "{{ full_image_name }}"
    tag: "{{ tag }}"
    source: build