---
- name: Build an image and push it to a private repo
  community.general.docker_image:
    build:
      path: "{{ path_to_dockerfile }}"
    name: "{{ full_image_name }}"
    tag: "{{ tag }}"
    source: build